### ISSUE TITLE
Strategy for handling errors in chain service

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#713] opened 2022-05-25 15:03 UTC
Open questions:
- Is a fatal error in the chain service a fatal error in the client (assuming there are no chain service restarts for now)?
- How should the fatal error get passed to chain service consumers?

**Comment by geoknee** [comment] 2022-07-19 11:46
Duplicate of #770

**Closed by geoknee** 2022-07-19 11:46 UTC
