### ISSUE TITLE
Define the lifecycle of a `ConsensusChannel`

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#422] opened 2022-03-28 21:39 UTC

**Comment by andrewgordstewart** [comment] 2022-03-28 21:58
FYI I chatted a bit about this with George [this morning](https://www.notion.so/statechannels/ConsensusChannel-ecd41ddc8294414585edb6c33f316a4c#dba1f59581094e27bdb51fedc37f182b). It may make sense to:
- change the `Message` format to make constructing objectives explicit
- construct a ConsensusChannel before constructing the objective (so that a ConsensusChannel owns  DFO)

@geoknee Would you and Alex want to work through this?

**Comment by andrewgordstewart** [comment] 2022-03-29 20:22
Alex points out that Alice would not start a virtualfund objective before a ConsensusChannel exists in the store.

ie. if Alice receives

```
m = {
  id: 'virtual-fund-0xf00',
  someLedgerProposal: ...
}
```

then she must ALREADY have a ConsensusChannel somewhere!

Therefore, creating and storing the ConsensusChannel when the DFO succeeds makes sense. This solution is simple and easy to implement.

# Edge cases
## `m` still arrives
It is still possible that Irene sent `m` out of order. But this is a signal that Irene is not following protocol -- why is she sending a ledger proposal for a virtual-fund objective without a signed preFS in place? When Irene doesn't follow protocol, Alice should not cooperate with Irene.

## Quick ledger top up
This sequence of events could still happen:
1. Alice & Irene create a DFO for a ledger channel
2. From Irene's perspective, the DFO succeeds. Irene stores a new (running) ConsensusChannel
3. Irene decides to start a ledger top-up and sends a ledger proposal
4. Alice receives the ledger proposal before the DFO succeeds from her perspective

This edge case is unlikely -- why would Irene top up so soon? If it does happen, there are reasonable ways of handling it:
- Alice returns a "ledger not found" in response to (3)

**Comment by geoknee** [comment] 2022-04-01 10:28
In the model where a `ConsensusChannel` is spawned as a `directfund` objective completes, I think there an edge case where:

* Irene creates the final postfund signature and sends this in a message `M0` to Alice
* Irene's `directfund` objective completes and her wallet stores a `ConsensusChannel`
* Irene's wallet receives a request to virtually fund a channel. it succeeds and a `virtualfund` objective is spawned.
* Some message `M1` is sent from Irene to Alice that proposes the `virtualfund` objective
* Alice receives `M1`, and rejects the objective because no `ConsensusChannel`.
* Alice receives `M0` but it is too late.

This example is caused by message reordering, but I think it could also be caused by a race between handlers in a concurrent wallet. 

Perhaps it is not a catastrophic edge case. Irene's `virtualfund` objective can timeout and fail, and her application can try again (where it will likely now succeed). 

It might also be possible to get around the edge case by requiring Alice to be p0 (leader) in L and also p0 (proposer) in V. Then, the proposer of a virtual channel is blocked from proposing until the joiner of the virtual channel has _for sure_ completed their `directfund` objective, and has _very likely_ spawned the `ConsensusChannel`.  We can make _very likely_ into certainty by ensuring that crank side effects are not executed until the `ConsensusChannel` is stored. See #437.

**Comment by geoknee** [comment] 2022-04-04 16:27
Closing via #437 (we now **create** a `ConsensusChannel` at a well defined moment). We have not yet thought through other parts of the lifecycle: 

* challenging
* closing / deleting

There's also the question of what to do with the vanilla `Channel` that exists during the running of the `DirectFundObjective`. Does it live alongside the `ConsensusChannel` (I guess probably not), or does it get garbage collected at the aforementioned moment?

**Closed by geoknee** 2022-04-04 16:27 UTC
