### ISSUE TITLE
Ensure payment proxy client handles CORS properly

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1657] opened 2023-09-11 10:30 UTC
The client will likely be served from netlify, or at least a different origin than the proxy itself (probably digital ocean IP). 

Therefore it will be making cross origin requests. We need to make sure that will work.

**Comment by lalexgap** [comment] 2023-09-11 19:35
@geoknee was the first point resolved by https://github.com/statechannels/go-nitro/pull/1656? 

We can probably create a seperate CORS issue. I think CORS should be working but I haven't verified that recently.

**Comment by geoknee** [comment] 2023-09-12 15:53
No it wasn't actually. 

For more context, I was trying to point the client at a non-proxy endpoint. We should decide if that is something that we want to support or not. If not, maybe let's not let the user dial in any old URL since then we have to cope with many failure modes. 

For the CORS error (same context as above), I get: 

```
localhost/:1 Access to fetch at 'https://magmo.com/force-move-games.pdf?channelId=0xcf82f1755d07e8bf27e7ae4a6bab46146d05a79e5523beab2af949a5ab01fbef&amount=412&signature=0x5625a3a932e470a04c82ac1fa2893abbb92da300dc3a4a5a397a5e225dedf8646cfe45d35cc4e028be9978685340c2ab4bb1a93c6ba1ec5981168fe465475d271b' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

in the browser console.

**Comment by lalexgap** [comment] 2023-09-12 17:35
Closing as this was due to us miss-using the UI. The proxy URL textbox accepts the URL of the payment proxy not the file you want to download. So when we put https://magmo.com/force-move-games.pdf into that textbox, the payment client is assuming that payment proxy is running on https://magmo.com/force-move-games.pdf.

Right now if you want to change the destination of the proxy you have to pass in a[ different ](https://github.com/statechannels/go-nitro/blob/2eb39373526155d28aec36ccac9c8f6f1d017d31/cmd/start-payment-proxy/main.go#L40)destination[ flag ](https://github.com/statechannels/go-nitro/blob/2eb39373526155d28aec36ccac9c8f6f1d017d31/cmd/start-payment-proxy/main.go#L40)when starting the proxy. I've confirmed that this works correctly and CORS is not an issue.

**Comment by lalexgap** [comment] 2023-09-12 17:36
Closing this as CORS is handled properly, we were just trying to use a non-proxy URL. The textbox accepts the URL of the payment proxy, not the url of the resource we want to fetch.

**Closed by lalexgap** 2023-09-12 17:36 UTC

**Comment by geoknee** [comment] 2023-09-12 18:22
> Closing this as CORS is handled properly, we were just trying to use a non-proxy URL. The textbox accepts the URL of the payment proxy, not the url of the resource we want to fetch.

Should the client make a distinction between a proxy and the resource we want to fetch? What's the difference, really? Is it the inclusion of the payment information?
