### ISSUE TITLE
Consider simplifying gas benchmarks

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1589] opened 2023-08-24 19:15 UTC
Currently our gas benchmarks are basically implemented in two places:

1.  In [ExportBenchmarkResults.ts](https://github.com/statechannels/go-nitro/blob/main/nitro-protocol/gas-benchmarks/exportBenchmarkResults.ts) we run through a bunch of use cases to generate the gas report.
2. In [Benchmark.test.ts](https://github.com/statechannels/go-nitro/blob/main/nitro-protocol/gas-benchmarks/benchmark.test.ts) we run through a bunch of uses cases to compare against the gas report.

This means when adding a new benchmark you need to implement the test scenario in two places (and in slightly different ways). Ideally we should be able to implement the test scenarios in one place.

**Comment by geoknee** [comment] 2023-08-24 20:02
Duplicate of #809

**Closed by geoknee** 2023-08-24 20:02 UTC
