### ISSUE TITLE
Implement RPC endpoint authentication

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1427] opened 2023-07-11 17:50 UTC
Currently our RPC server will accept connections from anyone. This is incredibly insecure as anyone who is able to access the RPC server can command it to send funds wherever.

Instead we should require some kind of authentication token to protect access to the RPC server. We may want to look at how Lotus does this and copy that.

**Comment by geoknee** [comment] 2023-07-11 20:05
> In the universe of `nitro-as-a-sidecar` rather than `nitro-as-a-networked-service` there's the option to only accept connections from the local machine.

Good point, but I suppose there might still be attack vectors from malware?

**Comment by geoknee** [comment] 2023-07-11 20:05
Also this is a duplicate of #1415

**Comment by NiloCK** [comment] 2023-07-14 12:42
Closing as duplicate of #1415

**Closed by NiloCK** 2023-07-14 12:42 UTC
