### ISSUE TITLE
 waitTimeForCompletedObjectiveIds can consume objectives it's not interested in 

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1114] opened 2023-02-07 22:07 UTC
> > However `waitTimeForCompletedObjectiveIds` will greedily read any completed objectives from the client, even if it's not the objective it's waiting for.
> 
> Is this the API behavior that we want?

Probably not.  I think there's two options we could look at to solve this:
1. Change `waitTimeForCompletedObjectiveIds` so it polls the client for the status. That way we don't have to worry about consuming from the `CompletedObjectives` in the wrong function.
2. Implement a struct like the the [completion monitor](https://github.com/statechannels/go-nitro-testground/blob/main/utils/monitor.go) that records objective completion and can be queried for the status of an objective.

_Originally posted by @lalexgap in https://github.com/statechannels/go-nitro/issues/1113#issuecomment-1421524655_

**Comment by kerzhner** [comment] 2023-02-16 18:48
https://github.com/statechannels/go-nitro/issues/1119 is a duplicate of this issue.

**Comment by geoknee** [comment] 2023-02-21 17:47
It would be nice if the solution also worked around the race condition between the objective completing and the `waitTimeForCompletedObjectiveIds` call being made. In other words, `waitTimeForCompletedObjectiveIds` should return immediately (and not hang forever) if the objective has already completed.

**Comment by geoknee** [comment] 2023-02-21 17:47
Also, I think there is a good case for including the solution in the production code, not just a helper function.

**Closed** 2023-03-23 13:48 UTC
